name: dio_cache
description: http cache lib for Flutter dio like RxCache.
version: 0.0.1
author: Hurshi
homepage: https://github.com/hurshi/dio-cache

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  quiver: ^2.0.3
  json_serializable: ^3.0.0
  dio: ^2.1.10
  sqflite: ^1.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
